### ISSUE TITLE
Add Token Not Working Consistently 

### ISSUE THREAD

**Issue by nitishpatel** [XDCFoundation/xdc-pay-xdcpay#12]
**Describe the bug**
The Add Token Feature to add any XRC20 tokens to wallet is giving issues, It seems to work fine for a certain accounts and not work for certain accounts.
**To Reproduce**
1. Open Your Wallet
2. Click on Tokens, and then click on Add Token
3. Enter your Token Address, It should fetch the Token Details and  it Auto Populate the remaining fields.

Token Address Tried with: xdcF9Ab4758de619952649e10A745BCf015530A0FAB

**Expected behavior**
On Address input,  Wallet should fetch the token details consistently for all the tokens.

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/39486276/187863299-a413c608-d3af-4d53-af09-d96e1c4aa474.png)

**Browser details (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome

**Comment by lucksin3** [comment]
This issue has been resolved on the latest version of XDCPay, please upgrade the XDCPay to version 6.2.12
