### ISSUE TITLE
XDCPay Random Loading Screens Pop Up / Hanging

### ISSUE THREAD

**Issue by nitishpatel** [XDCFoundation/xdc-pay-xdcpay#13]
**Describe the bug**
XDCPay randomly shows loading screen for an indefinite time. Unless Wallet is Restarted.

**To Reproduce**
Noticed While:
1 - Account Switching
2 - On Click Of Send / Transfer 
3 - Network Change  

**Expected behavior**
Wallet should not hang or a give a clear reason for the same.

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/39486276/187864178-ce6b30dd-6461-46d5-adb1-92e0908b00bd.png)

**Browser details (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome

**Comment by lucksin3** [comment]
This issue should be resolved in the latest XDCPay update. Please upgrade to version 6.2.12
