### ISSUE TITLE
unable to install dependencies

### ISSUE THREAD

**Issue by nitishpatel** [XDCFoundation/xdc-pay-xdcpay#5]
Tried running this extension on localhost having issues installing dependencies have tried using the node version mentioned in the .nvmrc
![image](https://user-images.githubusercontent.com/39486276/174577253-d67e880d-3bae-4de6-865d-3378f7b4166d.png)

**Comment by WalterBlueu** [comment]
Hi @nitishpatel I am reaching out to the devs who last worked on that repository asking for clarity on dependency versions, I will respond with more information.

**Comment by nitishpatel** [comment]
Thanks @WalterBlueu awaiting response, as we have already tried running through the steps and versions mentioned in the  README but none Seems to work.

**Comment by WalterBlueu** [comment]
@nitishpatel I got this from the devs:

1. remove material ui core package
2. then add all the dependencies using 'npm install'
3. if success , then add material ui core package

Please provide feedback on if these steps help

**Comment by nitishpatel** [comment]
@WalterBlueu  `npm install` does work but it still has issues with the `node_modules` and  running the `npm run dist` has problems 
![image](https://user-images.githubusercontent.com/39486276/175232897-89f569ff-5939-4551-a581-77d04254774c.png)

**Comment by WalterBlueu** [comment]
thank you @nitishpatel, I am forwarding this information on and will reply with more information when I receive it.

**Comment by WalterBlueu** [comment]
Hi @nitishpatel please try the following steps:

- Delete the node modules folder
- Then repeat the previous steps again
- Then try 'gulp dist' and 'npm run start' command
- Then try 'npm run dist'

Basically 'gulp dist' and 'npm run dist' command are same. After running either of these command we can execute 'npm run start' command.

**Comment by nitishpatel** [comment]
Nope still the same issue

**Comment by lhtkajalbobal** [comment]
Hi @nitishpatel , When I was working on XDCPay I had forked branch and took pull from xx-1358 .That forked branch is working fine in my system. I have also raised a pull request for it. Can I merge that code in a new branch in xdc foundation repo? Or you can take reference from the pull request changes. Let me know if it works for you.
Thanks

**Comment by nitishpatel** [comment]
Hi @lhtkajalbobal , I tried checking out the pr itself and was able to install the modules and also compile it, However, there is a small issue I faced while compiling its a case issue.
The file tries to 
`import Contacts from ./Contacts` 
However the file name is in lowercase hence I have changed that and the compilation works fine.
Can you try `npm run dist` on your end once and if the same issue persists include that in the PR?

![image](https://user-images.githubusercontent.com/39486276/177697525-5dceb358-7571-470e-ba3f-54c8d7856f2c.png)

**Comment by lhtkajalbobal** [comment]
Hi  @nitishpatel ,I have tried `npm run dist` at my end, it is working fine. You can try the installation steps again after resolving the import error and deleting the node modules folder.Let me know if it works.

<img width="1465" alt="Screenshot 2022-07-07 at 11 48 16 AM" src="https://user-images.githubusercontent.com/83451253/177704935-1cb8a4fd-b4e2-4206-bc3f-0bd8db84ffbe.png">

<img width="1506" alt="Screenshot 2022-07-07 at 11 36 07 AM" src="https://user-images.githubusercontent.com/83451253/177705056-47fe2437-3788-4f76-8e32-371bb05a8d87.png">

**Comment by nitishpatel** [comment]
Yeah @lhtkajalbobal Has mentioned in my previous comment, I was able to fix compile the code after fixing the import error

**Comment by lhtkajalbobal** [comment]
Hi , @nitishpatel  I had run `npm run dist` at my end and no issue occured including the PR code.Thanks.
