### ISSUE TITLE
Codebase for V6.2.10

### ISSUE THREAD

**Issue by nitishpatel** [XDCFoundation/xdc-pay-xdcpay#7]
I can't seem to find a proper working codebase for the v6.2.10 which is currently available in the market, can someone let me know the appropriate branch and commit which has the stable commit for the same. I have already tried the development branch and [commit](https://github.com/XDCFoundation/xdc-pay-xdcpay/commit/22ba552ea4f6da715dd85cacb170048d0a1b1d18.) which is giving me a white screen on compilation
  
![image](https://user-images.githubusercontent.com/39486276/178544007-bde9df5b-5c6d-4be2-894f-317408d96972.png)

Post this commit the version no seems to be 6.3.0.

**Comment by lhtYashMohan** [comment]
**Steps to follow for XDCPay**

1. Extract the zip file "**xdcpay-node-module**".
2. It contains the folder "**node_modules**".
3. Copy it in **xdcpay** working project. If there is node_modules folder already, then delete it first then paste the new one.
4. Remove package-lock.json if it is there.
5. In terminal run command "**npm i**" or "**npm install**".
6. Then run command "**npm start**".

[https://drive.google.com/file/d/19qvxm2vi8KPOUKs0V3AtIahADs9z89WO/view?usp=sharing](https://drive.google.com/file/d/19qvxm2vi8KPOUKs0V3AtIahADs9z89WO/view?usp=sharing)

**Comment by nitishpatel** [comment]
@lhtYashMohan Checking it, can you share the branch name and commit id which has codebase for version 6.2.10 which is live on the Chrome store?

**Comment by nitishpatel** [comment]
@lhtYashMohan  Got this error using the node modules shared.
![image](https://user-images.githubusercontent.com/39486276/178983642-63ad4923-23b1-41f2-a38b-03ac25205761.png)

I am using this commit: https://github.com/XDCFoundation/xdc-pay-xdcpay/commit/22ba552ea4f6da715dd85cacb170048d0a1b1d18.

**Comment by lhtYashMohan** [comment]
@nitishpatel Please take checkout from Development branch only and follow the above reply the steps to setup XDCPay.
This branch will definitely run fine on the system locally.

**Comment by nitishpatel** [comment]
> @nitishpatel Please take checkout from Development branch only and follow the above reply the steps to setup XDCPay.
> This branch will definitely run fine on the system locally. 

@lhtYashMohan We have done that however Rohit from XDCFoundation has asked us to get the 6.2.10 version

**Comment by lhtYashMohan** [comment]
![28799178-dcf6-48b6-8921-4da98a4077eb](https://user-images.githubusercontent.com/107236407/179962220-1177887c-2fb6-4f49-b8d8-57597d1890bf.jpg)
![32bde0e7-6252-487b-a939-8cbda841b843](https://user-images.githubusercontent.com/107236407/179962253-93c1e160-232a-4a4d-9440-fb92fb051fbe.jpg)


@nitishpatel I took the clone of same commit `22ba552` and its running absolutely fine in my local and you see it in screenshot too . I followed the same steps to setup with the  solution which i replied earlier.
 
So try it again with same steps.

**Comment by nitishpatel** [comment]
Thanks , Working , Any particular reason to use the node_modules zip file? @lhtYashMohan

**Comment by lhtYashMohan** [comment]
Yes, This node_module folder having some of package which already been deprecated and project is depending on it  which can't be downloaded now with `npm install` as it download new packages instead of deprecated one which are in package.json .

**Comment by nitishpatel** [comment]
@WalterBlueu @lucksin3 We were investigating the few issues raised by us like AddToken and  Wallet Hanging, on which we found that the compiled zip file version 6.2.10 shared by @lucksin3 works fine however the current release doesn't.
So Upon investigation, we found that the commit shared with us https://github.com/XDCFoundation/xdc-pay-xdcpay/commit/22ba552ea4f6da715dd85cacb170048d0a1b1d18 wasn't stable itself and had both AddToken and Wallet Handing Issues.

So can we get the commit id using which 6.2.10 Code version went live on the store?

**Comment by nitishpatel** [comment]
@lucksin3 @WalterBlueu any updates on the codebase commit?

**Comment by lhtYashMohan** [comment]
[22ba552](https://github.com/XDCFoundation/xdc-pay-xdcpay/tree/22ba552ea4f6da715dd85cacb170048d0a1b1d18)

This was the last code base which went live and was working fine.

**Comment by nitishpatel** [comment]
We have done our work on top of this only, but its buggy, which is also confirmed by @lucksin3

**Comment by lucksin3** [comment]
Closing this issue, codebase issue has been resolved.
